version: '3.8'
services:
  db:
    image: postgres:13
    container_name: pgdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: url_shortener_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 72metra
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      sh -c "python urlshortener/manage.py migrate &&
             python urlshortener/manage.py runserver 0.0.0.0:8000"
    container_name: django
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: url_shortener_db
      DB_USER: postgres
      DB_PASS: 72metra
      DB_PORT: 5432
      DJANGO_SETTINGS_MODULE: urlshortener.settings

  celery:
    build: .
    command: celery -A urlshortener worker --loglevel=info -P solo
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=urlshortener.settings
    depends_on:
      - web
      - redis

  redis:
    image: "redis:alpine"

volumes:
  postgres_data:
