# Generated by Django 5.0.1 on 2024-02-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0003_shortenedurl_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortenedurl",
            name="screenshot",
            field=models.ImageField(blank=True, null=True, upload_to="screenshots/"),
        ),
        migrations.AlterField(
            model_name="shortenedurl",
            name="short_id",
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
