# Generated by Django 5.0.1 on 2024-02-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0004_shortenedurl_screenshot_alter_shortenedurl_short_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortenedurl",
            name="screenshot",
            field=models.TextField(blank=True, null=True),
        ),
    ]
